# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasks < Formula
  desc ""
  homepage ""
  version "0.0.1"
  license "Unlicense"

  on_macos do
    url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Darwin_all.tar.gz"
    sha256 "25cf8886a3c1ee0437a936b3a9723c9e568ecd61f4ee9a60689d31052d828cd1"

    def install
      bin.install "goprojects-todo-list_0.0.1"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Linux_x86_64.tar.gz"
        sha256 "51bad5c322257229e2519537231ccac1c81b1075f77b1576079ad6a7c546a043"

        def install
          bin.install "tasks"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Linux_armv6.tar.gz"
        sha256 "c452bac4f341896aac2c133b94fa2e374d377f4ff6d0a843a44447ce04eb24f3"

        def install
          bin.install "tasks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Linux_arm64.tar.gz"
        sha256 "66b94db79f4831610e9186a722b4bce2dcb57618ee43c2190e3432325a4c2de5"

        def install
          bin.install "tasks"
        end
      end
    end
  end
end
