# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasks < Formula
  desc "A simple todo list manager for the command line"
  homepage "https://postrausch.tech"
  version "0.0.1"
  license "Unlicense"

  on_macos do
    url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Darwin_all.tar.gz"
    sha256 "77b1cab60db5298cf88007a8f5f8ae8d40fe655c420fc27892e8961e568236fd"

    def install
      bin.install "goprojects-todo-list_0.0.1"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Linux_x86_64.tar.gz"
        sha256 "aa46653a8a2a19958b39c027ca5ca0ffb3905067a7d8e80bd5ec66ac8de5e370"

        def install
          bin.install "tasks"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Linux_armv6.tar.gz"
        sha256 "d93be5d5913d5f8d8e5d33c8ac38b92a1977725c06ac4fe082a5ad41381d4421"

        def install
          bin.install "tasks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Linux_arm64.tar.gz"
        sha256 "2783678260b3a38844400ae6cbb9ea4640443dd598628e0c3720e2f886e2aa1b"

        def install
          bin.install "tasks"
        end
      end
    end
  end
end
