# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasks < Formula
  desc "A simple todo list manager for the command line"
  homepage "https://postrausch.tech"
  version "0.0.1"
  license "Unlicense"

  on_macos do
    url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Darwin_all.tar.gz"
    sha256 "8118103cc41dc54f75b7ca75156248850145f6b14325079cee682c88745817e0"

    def install
      bin.install "goprojects-todo-list_0.0.1"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Linux_x86_64.tar.gz"
        sha256 "4b23dcc00fd50beb9da39bf097cb948d656b85ade9c27660e3f2a5cdadeab629"

        def install
          bin.install "tasks"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Linux_armv6.tar.gz"
        sha256 "9b70378041fa8192a3998ba22a541885e5b683cc03d9a9b74cced4ccd8a8a27a"

        def install
          bin.install "tasks"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hra42/goprojects-todo-list/releases/download/v0.0.1/goprojects-todo-list_Linux_arm64.tar.gz"
        sha256 "50547b3a153e341ffe874a90a1bac94d309be559ccbe761381816a068267a696"

        def install
          bin.install "tasks"
        end
      end
    end
  end
end
